### PR TITLE
When converting to a Unix path, avoid double trailing slashes

### LINKED ISSUE #112: cygpath roundtrip produces double slash: cygpath -u ``cygpath -m /`` -> `//`
### Description

cygpath roundtrip produces double slash

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19045.2130]

### Expected behavior

/

### Actual behavior

//

### Repro steps

```sh
$ cygpath -u `cygpath -m /`
//
```

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by dscho**
This fixes https://github.com/msys2/msys2-runtime/issues/112

### CODE REVIEW

File: winsup/cygwin/mount.cc [hunk 1]
```diff
@@ -925,6 +925,9 @@ mount_info::conv_to_posix_path (const char *src_path, char *posix_path,
       int addslash = nextchar > 0 ? 1 : 0;
       if ((mi.posix_pathlen + (pathbuflen - mi.native_pathlen) + addslash) >= NT_MAX_PATH)
 	return ENAMETOOLONG;
+      /* avoid appending a slash if the result already has a trailing slash */
```
Comment (lazka) [inline winsup/cygwin/mount.cc:926]: Shouldn't this be above the ENAMETOOLONG check?

Comment (dscho) [reply winsup/cygwin/mount.cc:926]: True.

Comment (dscho) [reply winsup/cygwin/mount.cc:926]: Fixed.

**Review by lazka — APPROVED** [review]
