### PR TITLE
Handle Ctrl+C interupts for Mingw Executables

### LINKED ISSUE #29: Handle Ctrl+C interupts for Mingw Executables
see https://github.com/msys2/MINGW-packages/issues/7650

Simple reproducer,
- open minitty
- Install MinGW-python
- run `python`
- Press Ctrl+C
traceback would be missing in minitty while the same is should when python is run in cmd

This cause the executable from setuptools, like `pip.exe` to not kill the child process as described https://github.com/msys2/MINGW-packages/issues/7650

When discussing on [Discord](https://discord.com/channels/792780131906617355/794220101741838401/815593216329515050) a few days ago, lazka pointed out that this is fixed in Git for Windows runtime.

The corresponding issue on Git for Windows: https://github.com/git-for-windows/git/issues/1248
These are the patches:
- https://github.com/git-for-windows/msys2-runtime/commit/e8dd881efeb5632e861e214db7686d868a420038
- https://github.com/git-for-windows/msys2-runtime/commit/24fb4e4b1c55753a38ac472d7b8f1ba59b0eee6c
- https://github.com/git-for-windows/msys2-runtime/commit/3c7a25ef94adc222f7f83fb10e453201f3d6ec57
- https://github.com/git-for-windows/msys2-runtime/commit/0a1f55b738ef3970fdcc155d6d8fc29dc1d7596e

### PR DESCRIPTION
**Pull request by naveen521kk**
cherry-picked from

- https://github.com/git-for-windows/msys2-runtime/commit/e8dd881efeb5632e861e214db7686d868a420038
- https://github.com/git-for-windows/msys2-runtime/commit/24fb4e4b1c55753a38ac472d7b8f1ba59b0eee6c
- https://github.com/git-for-windows/msys2-runtime/commit/3c7a25ef94adc222f7f83fb10e453201f3d6ec57
- https://github.com/git-for-windows/msys2-runtime/commit/0a1f55b738ef3970fdcc155d6d8fc29dc1d7596e

cc @dscho

there were conflicts while picking tried my best to fix them say if they were wrong :wink:

Fixes https://github.com/msys2/msys2-runtime/issues/29

### CODE REVIEW

**Comment by dscho** [comment]
Could you squash the last commit into the one wit the incorrect merge conflict resolution?

Also, could you download https://github.com/msys2/msys2-runtime/suites/2262965199/artifacts/47141681 and verify that it does, indeed, fix the Ctrl+C problem?

**Comment by naveen521kk** [comment]
> Also, could you download https://github.com/msys2/msys2-runtime/suites/2262965199/artifacts/47141681 and verify that it does, indeed, fix the Ctrl+C problem?

Could you help me on how to install it?

**Comment by naveen521kk** [comment]
I think I have to cherry-pick from https://github.com/git-for-windows/msys2-runtime/commit/25c4c018b282bacd07403d40219c967a39311b1c also

**Comment by dscho** [comment]
> > Also, could you download https://github.com/msys2/msys2-runtime/suites/2262965199/artifacts/47141681 and verify that it does, indeed, fix the Ctrl+C problem?
> 
> Could you help me on how to install it?

Yes. You _could_ simply extract this over an existing MSYS2 installation, but all you _really_ want is to replace the `usr/bin/msys-2.0.dll` file (you cannot do that from inside MSYS2, though, because that DLL cannot be in use while you replace it).


> I think I have to cherry-pick from [git-for-windows/msys2-runtime@25c4c01](https://github.com/git-for-windows/msys2-runtime/commit/25c4c018b282bacd07403d40219c967a39311b1c) also

Yes, this is crucial to be able to interrupt processes running in a different CPU architecture than the MSYS2 runtime itself.

BTW I think 2153eb06dc is not needed: it tries to export a function that is no longer an exported function, but an inline function instead.

About 42f68af7c8... I dropped it from Git for Windows. The rationale is that the processes that are getting interrupted need to make sure _themselves_ that their child processes are reaped, too.

**Comment by naveen521kk** [comment]
It looks like it is working for me. I did a new install from tar archive and pasted the contents of the zip file on that and opened the `mingw64.exe`. Then I run `pacman -S mingw-w64-x86_64-python`
and then `python -c "import time;time.sleep(40)"`,  and pressing Ctrl+C printed a traceback exited, which means it was *killed* correctly.
```sh
$ python -c "import time;time.sleep(40)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyboardInterrupt
```
I will look into your comments and change things soon.

**Comment by naveen521kk** [comment]
> BTW I think 2153eb0 is not needed: it tries to export a function that is no longer an exported function, but an inline function instead.
> About 42f68af... I dropped it from Git for Windows. The rationale is that the processes that are getting interrupted need to make sure themselves that their child processes are reaped, too.

I am dropping https://github.com/msys2/msys2-runtime/commit/2153eb06dc837b7690b7123eb0480d21e013fe05 and https://github.com/msys2/msys2-runtime/commit/42f68af7c82113c4b9c8bce680060d55b7309580

**Comment by naveen521kk** [comment]
Also, it works. But randomly triggers AntiVirus saying it does something malicious and deletes `bash.exe`. While this doesn't happen with git-for-windows one, I wonder why? Maybe I missed any patches? Or AV ignores the `Program Files` directory things?

**Comment by dscho** [comment]
> 
> 
> Also, it works. But randomly triggers AntiVirus saying it does something malicious and deletes `bash.exe`. While this doesn't happen with git-for-windows one, I wonder why? Maybe I missed any patches? Or AV ignores the `Program Files` directory things?

Well, the code _does_ inject a remote thread... So I can see why anti-malware would be triggered, even if it is wrong.

And I have no idea why Git for Windows does not trigger this... I have no insight into how these anti-malware programs work.

**Comment by naveen521kk** [comment]
That shouldn't be a problem for me because I have excluded it from scanning the Msys2 directory. 
(All this happened because I did a new install for testing this, or else I wouldn't have told about this.)

**Comment by dscho** [comment]
Hey, but here's an idea: we already use those `getprocaddr` helpers to look up the address of `ExitProcess()` and `CtrlRoutine()`. If we now teach `getprocaddr` to also _inject_ the remote thread, then the anti-malware might trigger on just those two small programs, and they can be excluded specifically from the anti-malware (and if they're quarantined, we can still fall back to `TerminateProcess()`).

What do you think, @naveen521kk?

**Comment by naveen521kk** [comment]
> Hey, but here's an idea: we already use those getprocaddr helpers to look up the address of ExitProcess() and CtrlRoutine(). If we now teach getprocaddr to also inject the remote thread, then the anti-malware might trigger on just those two small programs, and they can be excluded specifically from the anti-malware (and if they're quarantined, we can still fall back to TerminateProcess()).

Should be better. 
But still excluding those two programs seems useless to me. I once had `pacman.exe` removed when I was doing an update and AV thought it as ransomware and quarantined it. So, full msys2 installation needs to be excluded anyhow.

**Comment by dscho** [comment]
> 
> 
> > Hey, but here's an idea: we already use those getprocaddr helpers to look up the address of ExitProcess() and CtrlRoutine(). If we now teach getprocaddr to also inject the remote thread, then the anti-malware might trigger on just those two small programs, and they can be excluded specifically from the anti-malware (and if they're quarantined, we can still fall back to TerminateProcess()).
> 
> Should be better.
> But still excluding those two programs seems useless to me. I once had `pacman.exe` removed when I was doing an update and AV thought it as ransomware and quarantined it. So, full msys2 installation needs to be excluded anyhow.

I think that is just a bug if anti-malware quarantines `pacman.exe`.

But with the injected remote thread, I think anti-malware is "less wrong"... So in my mind, if we do it right, and if anti-malware is not _overly_ overzealous, it should be enough to exclude those two helpers (or alternatively, hope that anti-malware developers will analyze the helpers, verify that they are mostly harmless, and add patterns that match those use cases specifically to avoid triggering on them).

**Comment by naveen521kk** [comment]
> I think that is just a bug if anti-malware quarantines pacman.exe.

Don't know, it was just once after that it didn't do anything there.


> But with the injected remote thread, I think anti-malware is "less wrong"... So in my mind, if we do it right, and if anti-malware is not overly overzealous, it should be enough to exclude those two helpers (or alternatively, hope that anti-malware developers will analyze the helpers, verify that they are mostly harmless, and add patterns that match those use cases specifically to avoid triggering on them).

Right. If they analyze `bash.exe` that would be useless for them as well, but there are possibilities that the AV could exclude those two helpers.
Maybe why not try?

**Comment by naveen521kk** [comment]
I will try to work on that tomorrow.

**Comment by naveen521kk** [comment]
> I will try to work on that tomorrow.

Looks like my knowledge with C and win32 API is so poor to do this. I think I won't be able to do it, sorry.

**Comment by naveen521kk** [comment]
@dscho after a long time, today I gave another attempt. https://github.com/msys2/msys2-runtime/pull/31/commits/e3eb220d56a1a0f446499b7528ed9238d12b5a8e

I don't know any way's to debug it, if you know please tell, it seems to not work finally when I downloaded the artifacts and tried it on new install.

**Comment by naveen521kk** [comment]
I was able to confirm by compiling the source of `getprocaddr` separately that it works.
For example, I tried `python -c "import time;time.sleep(1000)` in shell and then I run

```sh
test CtrlRoutine 0 2440
```
where `test.exe` is the compiled executable and `2440` is from `tasklist` command corresponding to `python.exe`. Python terminated with

```py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyboardInterrupt
```
which shows that it works.

**Comment by naveen521kk** [comment]
Here I pushed again, I think it should work?

File: winsup/cygwin/exceptions.cc [hunk 1]
```diff
@@ -1550,8 +1551,23 @@ sigpacket::process ()
...
+        case SIGSTOP:
+        case SIGTSTP:
+        case SIGTTIN:
+        case SIGTTOU:
+          system_printf ("Suppressing signal %d to win32 process (pid %u)",
+              (int)si.si_signo, (unsigned int)GetProcessId(ch_spawn));
+          goto done;
+        default:
+          sigproc_printf ("terminating captive process");
+          rc = exit_process_tree (ch_spawn, 128 + (sigExeced = si.si_signo));
```
Comment (naveen521kk) [inline winsup/cygwin/exceptions.cc:1573]: @dscho I am confused here. Why should `128` be added here while the previous `TerminateProcess` didn't have them? Can you explain?

Comment (naveen521kk) [reply winsup/cygwin/exceptions.cc:1573]: I am asking this because doing 
```cmd
test CtrlRoutine 0 9032
```
seem's to kill the process with traceback

while 
```cmd
test CtrlRoutine 1 9032
```
force kill it.

But
```cmd
test CtrlRoutine 128 9032
```
doesn't do anything.

Maybe that's the problem things not working?

Comment (naveen521kk) [reply winsup/cygwin/exceptions.cc:1573]: Maybe I am just confused.

**Comment by naveen521kk** [comment]
Yes finally, this works :tada:

File: winsup/cygwin/exceptions.cc (hunk 1 above)
Comment (dscho) [reply winsup/cygwin/exceptions.cc:1573]: The convention that signals result in exit codes equaling to 128 plus the signal number is explained e.g. here: https://stackoverflow.com/questions/1101957/are-there-any-standard-exit-status-codes-in-linux/1535733#1535733

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 2]
```diff
@@ -71,11 +74,11 @@ get_address_from_cygwin_console_helper(int bitness, wchar_t *function_name)
 
   STARTUPINFOW si = {};
   PROCESS_INFORMATION pi;
-  size_t len = wcslen (wbuf) + wcslen (function_name) + 1;
+  size_t len = wcslen (wbuf) + 1 + wcslen (function_name) + 1 + (exit_code == 0 ? 1 : (int)(log10 (exit_code) + 1)) + 1 + (pid == 0 ? 1 : (int)(log10 (pid) + 1));
```
Comment (dscho) [inline winsup/cygwin/include/cygwin/exit_process.h]: Oy! That's a lot of CPU spent on calculating the size we need to allocate to fix the exit code.

Since exit codes are limited to three digits (7 bits, to be precise, or 8 bits if you accommodate for signals), and process IDs are [limited to `DWORD`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getprocessid) (AKA 32-bit `unsigned long`) all we need is to change that `+ 1` to `+ 3 /* exit code */ + 1 /* space */ + 10 /* process ID, i.e. DWORD */ + 1 /* NUL */;`

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 3]
```diff
@@ -71,11 +74,11 @@ get_address_from_cygwin_console_helper(int bitness, wchar_t *function_name)
...
   WCHAR cmd[len + 1];
   WCHAR title[] = L"cygwin-console-helper";
 
-  swprintf (cmd, len + 1, L"%S %S", wbuf, function_name);
+  swprintf (cmd, len + 1, L"%S %S %d %d", wbuf, function_name, exit_code, pid);
```
Comment (dscho) [inline winsup/cygwin/include/cygwin/exit_process.h]: That second `%d` needs to be `%ld` to accommodate for a `DWORD` (which really is an `unsigned long`).

File: winsup/utils/getprocaddr.c [hunk 4]
```diff
@@ -43,22 +80,22 @@ ctrl_handler(DWORD ctrl_type)
 				 &address, NULL);
   if (count != 1)
     {
-      output (1, "Could not capture backtrace\n");
+    output (1, "Could not capture backtrace\n");
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: Let's not introduce white-space issues. (This not only applies here, but to similar changes further below.)

File: winsup/utils/getprocaddr.c [hunk 5]
```diff
@@ -82,65 +124,66 @@ main (int argc, char **argv)
...
-      void *address = (void *) GetProcAddress (kernel32, argv[1]);
+    void *address = (void *) GetProcAddress (kernel32, argv[1]);
       if (!address)
         return 1;
-      output (0, "%p\n", address);
+    output (0, "%p\n", address);
       return 0;
     }
+  exit_code = atoi(argv[2]);
+  pid = atoi(argv[3]);
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: This needs to be `strtoul()` because the process ID is an `unsigned long` (or, `DWORD`, which is the same).

File: winsup/utils/getprocaddr.c [hunk 6]
```diff
@@ -82,65 +124,66 @@ main (int argc, char **argv)
...
 
   /* Special-case kernel32!CtrlRoutine */
-  if (argc == 3 && !strcmp ("--alloc-console", argv[2]))
+  if (argc == 5 && !strcmp ("--alloc-console", argv[4]))
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: Umm... why?

I do not actually see any code where this is used, and have to assume that I only needed this for testing purposes... Therefore, this entire `Special-case CtrlRoutine` clause should be dropped.

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 7]
```diff
@@ -40,14 +41,15 @@
...
+#include <math.h>
 
 #ifndef __INSIDE_CYGWIN__
 /* To help debugging via kill.exe */
 #define small_printf(...) fprintf(stderr, __VA_ARGS__)
 #endif
 
 static LPTHREAD_START_ROUTINE
-get_address_from_cygwin_console_helper(int bitness, wchar_t *function_name)
+get_address_from_cygwin_console_helper_and_inject_remote_thread(int bitness, wchar_t *function_name, int exit_code, DWORD pid)
```
Comment (dscho) [inline winsup/cygwin/include/cygwin/exit_process.h]: That's an awfully long function name. How about using the name `kill_via_console_helper()` instead?

**Review by dscho — COMMENTED** [review]
This looks pretty good already!

Eventually, I would love to break this change apart and fold it into the earlier commits (feel free to mark yourself as co-author via the `Co-authored-by:` footer) because that will make it easier to maintain the MSYS2-specific patches on top of Cygwin.

**Comment by naveen521kk** [comment]
> Eventually, I would love to break this change apart and fold it into the earlier commits (feel free to mark yourself as co-author via the Co-authored-by: footer) because that will make it easier to maintain the MSYS2-specific patches on top of Cygwin.

Sure, but only after this is ready to merge.

File: winsup/utils/getprocaddr.c (hunk 4 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: I don't know how this came, maybe something is automatically formatting it? Anyway, I will change.

File: winsup/utils/getprocaddr.c (hunk 6 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: I will remove it.

File: winsup/cygwin/include/cygwin/exit_process.h (hunk 2 above)
Comment (naveen521kk) [reply winsup/cygwin/include/cygwin/exit_process.h]: Done https://github.com/msys2/msys2-runtime/pull/31/commits/cc10c797854fa2c4086b493eba20856738a8934c

File: winsup/cygwin/include/cygwin/exit_process.h (hunk 3 above)
Comment (naveen521kk) [reply winsup/cygwin/include/cygwin/exit_process.h]: Done https://github.com/msys2/msys2-runtime/pull/31/commits/ced32fb6d72f2dfbbf1d6026481d8c1c44742e4b

File: winsup/utils/getprocaddr.c (hunk 4 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Done https://github.com/msys2/msys2-runtime/pull/31/commits/585f456cde1115f5126efcef802db0ec19c739a6

File: winsup/utils/getprocaddr.c (hunk 5 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Done https://github.com/msys2/msys2-runtime/pull/31/commits/27e6f3d407281170d325bcf9de2286b2ae415aed

File: winsup/utils/getprocaddr.c (hunk 6 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Done https://github.com/msys2/msys2-runtime/pull/31/commits/a2da9e9a73dfb229ce2e9402c1b6c8f5645e768d

File: winsup/cygwin/include/cygwin/exit_process.h (hunk 7 above)
Comment (naveen521kk) [reply winsup/cygwin/include/cygwin/exit_process.h]: Done https://github.com/msys2/msys2-runtime/pull/31/commits/b867fed81f4a30033b57fecd71d2d5274671931e

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 8]
```diff
@@ -0,0 +1,348 @@
...
+
+  si.cb = sizeof (si);
+  si.dwFlags = STARTF_USESHOWWINDOW | STARTF_USESTDHANDLES;
+  si.wShowWindow = SW_HIDE;
+  si.lpTitle = title;
+  si.hStdInput = si.hStdError = INVALID_HANDLE_VALUE;
+  si.hStdOutput = h[1];
+
+  /* Create a new hidden process.  Use the two event handles as
+     argv[1] and argv[2]. */
```
Comment (dscho) [inline winsup/cygwin/include/cygwin/exit_process.h]: I think this comment is now outdated.

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 9]
```diff
@@ -0,0 +1,348 @@
...
+	}
+      if (!count || buffer[offset] == '\n')
+	break;
+      offset += count;
+    }
+  CloseHandle(h[0]);
+
+  buffer[offset] = '\0';
+
+  return (LPTHREAD_START_ROUTINE) strtoull(buffer, NULL, 16);
```
Comment (dscho) [inline winsup/cygwin/include/cygwin/exit_process.h]: Since we're no longer interested in the routine's address, we can save ourselves a lot of trouble, returning the exit code of the spawned process instead. And removing the pump that reads the spawned process' `stdout`. And not even creating that pipe.

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 10]
```diff
@@ -0,0 +1,348 @@
...
+{
+  BOOL is_wow;
+  int bitness;
+  if (!get_wow (process, is_wow, bitness))
+    return NULL; /* could not determine */
+
+  if (bitness == 64)
+    {
+      static LPTHREAD_START_ROUTINE ctrl_routine_address;
+      if (!ctrl_routine_address)
```
Comment (dscho) [inline winsup/cygwin/include/cygwin/exit_process.h]: This logic is now incorrect, as we want to call the console helper _always_, not just the first time. Therefore, that `ctrl_routine_address` should not be `static`.

In fact, we do not need that `ctrl_routine_address` anymore at all. Only the helper needs to know it.

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 11]
```diff
@@ -0,0 +1,348 @@
...
+	  kill_via_console_helper (64, L"CtrlRoutine", exit_code, pid);
+      return ctrl_routine_address;
+    }
+
+  static LPTHREAD_START_ROUTINE ctrl_routine_address;
+  if (!ctrl_routine_address)
+    {
+      ctrl_routine_address =
+	kill_via_console_helper (32, L"CtrlRoutine", exit_code, pid);
+    }
```
Comment (dscho) [inline winsup/cygwin/include/cygwin/exit_process.h]: The difference between `bitness == 64` and `bitness == 32` now boils down to passing `bitness` as first parameter to `kill_via_console_helper()`. Therefore, we do not even need that `if (bitness == 64)` conditional at all anymore.

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 12]
```diff
@@ -0,0 +1,348 @@
...
+exit_one_process(HANDLE process, int exit_code, DWORD pid)
+{
+  LPTHREAD_START_ROUTINE address = NULL;
+  int signo = exit_code & 0x7f;
+
+  switch (signo)
+    {
+      case SIGINT:
+      case SIGQUIT:
+	address = get_ctrl_routine_address_for_process_and_inject_remote_thread(process, signo == SIGINT ?
```
Comment (dscho) [inline winsup/cygwin/include/cygwin/exit_process.h]: Since we do not use that address at all anymore, this call to `get_ctrl_routine_...()` could be replaced by a simple

```c
if (get_wow(process, is_wow, bitness) &&
    0 /* exit code 0 = success */ == kill_via_console_helper (bitness, L"CtrlRoutine",
                             signo == SIGINT ? CTRL_C_EVENT : CTRL_BREAK_EVENT, pid)))
            return 0;
```

File: winsup/utils/getprocaddr.c [hunk 13]
```diff
@@ -0,0 +1,174 @@
...
+    }
+
+  if (!GenerateConsoleCtrlEvent(CTRL_BREAK_EVENT, 0))
+    {
+    output (1, "Could not simulate Ctrl+Break\n");
+      return 1;
+    }
+
+  /* Give the event 1sec time to print out the address */
+  Sleep(1000);
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: This is no longer needed, as we do not require the address in the MSYS2 runtime, only in `getprocaddr`.

File: winsup/utils/getprocaddr.c [hunk 14]
```diff
@@ -0,0 +1,174 @@
...
+        return 1;
+      }
+
+      HINSTANCE kernel32 = GetModuleHandle ("kernel32");
+      if (!kernel32)
+        return 1;
+      void *address = (void *) GetProcAddress (kernel32, argv[1]);
+      if (!address)
+        return 1;
+      output (0, "%p\n", address);
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: We no longer need to print out the address, but we do need to instead inject the remote thread now.

File: winsup/utils/getprocaddr.c [hunk 15]
```diff
@@ -0,0 +1,174 @@
...
+}
+
+int
+main (int argc, char **argv)
+{
+  char *end;
+
+  if (argc < 4)
+    {
+      output (1, "Need a function name, exit code and pid\n");
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: Maybe it would make more sense to allow `argc == 2`, so that we do not have to change the name of the helper (`getprocaddr` implies that we _do_ print out an address, but we inject a remote thread calling that address instead. But if we allow `argc == 2` to print out the address, and only if `argc == 4` we inject the remote thread instead, the name of the executable still makes sense).

And now that I read all this, I remember why I needed that `--alloc-console` flag: if the calling process has the same bitness as the called process, they share a console, and if a Ctrl+C event is sent to that console, all processes attached to the same console are terminated. Including the MSYS2 runtime.

So I think that we will need to be a bit more careful here: I think the safest thing would be to _always_ attach a new console if `argv[1]` is `CtrlRoutine`, i.e. right before the `if (!SetConsoleCtrlHandler (ctrl_handler, TRUE))` line.

**Review by dscho — COMMENTED** [review]
This is exciting! I think the code is slowly getting into a really good shape, it's almost time to whip out `rebase -i` and split the work into a nice shape; My preferred story would look like this:

1. a commit introducing `getprocaddr32.exe` and `getprocaddr64.exe` that prints out the given function's address
2. a commit patching that console helper so that it can inject a remote thread calling the given function when called with the arguments <exit-code> and <pid>
3. a commit teaching the console helper to special-case the function name `CtrlRoutine`
4. a commit teaching the MSYS2 runtime to try to call that helper, falling back to `TerminateProcess()`
5. a commit teaching `kill.exe` to use the same code path

Once we're both satisfied with the shape of the overall diff, I can help with this.

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: > And now that I read all this, I remember why I needed that --alloc-console flag: if the calling process has the same bitness as the called process, they share a console, and if a Ctrl+C event is sent to that console, all processes attached to the same console are terminated. Including the MSYS2 runtime.

Yeah, I have seen that happen multiple times and was wondering what was the problem. After, that I thought that this shouldn't be called from minitty and then used cmd.

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: But this doesn't happen when I press `Ctrl+C` in the console though.

File: winsup/cygwin/include/cygwin/exit_process.h (hunk 10 above)
Comment (naveen521kk) [reply winsup/cygwin/include/cygwin/exit_process.h]: I am dropping this function. Looks like it is not needed.

**Comment by naveen521kk** [comment]
> I think the code is slowly getting into a really good shape, it's almost time to whip out rebase -i and split the work into a nice shape; My preferred story would look like this:

I don't want to force push until we both are satisfied or else it would be hard to track reviews.

File: winsup/utils/getprocaddr.c (hunk 13 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Looks like for Windows to send the Ctrl event about 1sec is needed. I tried experimenting it.

File: winsup/utils/getprocaddr.c (hunk 14 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Changed according to https://github.com/msys2/msys2-runtime/pull/31#discussion_r617422528

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Can you check if https://github.com/msys2/msys2-runtime/pull/31/commits/5cbbec772318bd7ef2376a6e0623eb0eeeb63c8d works?

**Comment by naveen521kk** [comment]
This works perfectly locally, and the code looks pretty much ok for me.

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (dscho) [reply winsup/utils/getprocaddr.c]: > 
> 
> Can you check if [5cbbec7](https://github.com/msys2/msys2-runtime/commit/5cbbec772318bd7ef2376a6e0623eb0eeeb63c8d) works?

I won't have time to actually try this, but from what I read, it looks good (although it has tons of whitespace changes, which makes the patch a bit hard to read).

File: winsup/utils/getprocaddr.c (hunk 13 above)
Comment (dscho) [reply winsup/utils/getprocaddr.c]: Of course! Thanks for double-checking.

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: I have tested it out locally before pushing and can say it works.

> (although it has tons of whitespace changes, which makes the patch a bit hard to read).

I have no idea why this happens each time when I edit something. Maybe vscode does some formatting changes automatically?

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: > I think the safest thing would be to always attach a new console if argv[1] is CtrlRoutine, i.e. right before the if (!SetConsoleCtrlHandler (ctrl_handler, TRUE)) line.

I think it is not needed, it works without that also.

Comment (dscho) [reply winsup/utils/getprocaddr.c]: The problem is that the `GenerateConsoleCtrlEvent()` call might take down the calling process. Which is kind of counterproductive if all you want is to figure out the address of the `CtrlRoutine` function ;-)

Comment (dscho) [reply winsup/utils/getprocaddr.c]: > Maybe vscode does some formatting changes automatically?

Probably.

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: I have previously tried `--alloc-console` and it produced a popup. Do we want to produce a popup every time the user wants to kill the program(by pressing Ctrl+C)?
Or that doesn't happen when called from runtime itself?

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: > Which is kind of counterproductive if all you want is to figure out the address of the CtrlRoutine function ;-)

Also, I just tried `/usr/libexec/getprocaddr32 CtrlRoutine`, the shell didn't kill itself
```bash
$ /usr/libexec/getprocaddr64 CtrlRoutine
0000000077a44810
Segmentation fault
```
no idea why "Segmentation fault". Is that all we need?

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: > Which is kind of counterproductive if all you want is to figure out the address of the CtrlRoutine function ;-)

We aren't injecting the remote thread when 2 args are passed or when want to find the address so I think we don't need to do so.

**Comment by naveen521kk** [comment]
@dscho Is there anything else I should do here for this to be merged?

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (dscho) [reply winsup/utils/getprocaddr.c]: > I have previously tried `--alloc-console` and it produced a popup

Then it uses incorrect parameters. There is a way to create a console and hide it before it is shown. I think you need to add a creation flag `CREATE_NEW_CONSOLE` and then set `STARTF_USESHOWWINDOW` in the startup info and then set `wShowWindow` to `SW_HIDE`.

> > Which is kind of counterproductive if all you want is to figure out the address of the CtrlRoutine function ;-)
> 
> We aren't injecting the remote thread when 2 args are passed or when want to find the address so I think we don't need to do so.

We are sending the control event in order to get the backtrace so that we can determine the address. We will get that address all right, but unfortunately the buck does not stop there: the control event is interpreted, and the programs attached to the same console are taken down (there seems to be some special handling for `cmd.exe` because, as you pointed out, it is not taken down by <kbd>Ctrl</kbd>+<kbd>C</kbd>).

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: > Then it uses incorrect parameters. There is a way to create a console and hide it before it is shown. I think you need to add a creation flag CREATE_NEW_CONSOLE and then set STARTF_USESHOWWINDOW in the startup info and then set wShowWindow to SW_HIDE.

:+1:  Maybe I try to do it later today.

> We are sending the control event in order to get the backtrace so that we can determine the address. We will get that address all right, but unfortunately the buck does not stop there: the control event is interpreted, and the programs attached to the same console are taken down (there seems to be some special handling for cmd.exe because, as you pointed out, it is not taken down by Ctrl+C).

I have seen that happen only when we inject a remote thread not otherwise(yes there is special handling for cmd.exe even when injecting a remote thread). I was able to call `getprocaddr64` present in Git Bash without the Git Bash being closed itself.
```sh
$ /usr/libexec/getprocaddr64 CtrlRoutine
00000000772e4810
Segmentation fault
```
Anyhow I will try implementing what you told.

Btw, how did you get buttons like on `Ctrl` + `C`?

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: I tried implementing it and I am unhappy with it. It nearly takes around 5-7 seconds extra than the previous implementation also wasn't able to use those executable on cmd(there was no output in cmd, IDK). Though I can confirm that the current implementation works without closing the original shell itself, I have tried it, on both cmd and bash.

Anyway, I attached the diff and don't want to push until you tell the `5-7` seconds extra time is ok.
[console.txt](https://github.com/msys2/msys2-runtime/files/6378723/console.txt)

Comment (dscho) [reply winsup/utils/getprocaddr.c]: Hmm. 5-7 seconds is not good at all. But I wonder where they come from... any idea?

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: > any idea?

No idea. But I can give data on how much time it really takes. here, `new.exe` is with this patch applied and `old.exe` is without this patch(same as in this PR now)

```sh
$ time ./new CtrlRoutine
0000000076e14810
Segmentation fault

real    0m10.100s
user    0m0.000s
sys     0m0.046s

$ time ./old CtrlRoutine
0000000076e14810
Segmentation fault

real    0m0.060s
user    0m0.015s
sys     0m0.015s
````

```sh
$ time ./new ExitProcess
0000000076f1c120
Segmentation fault

real    0m0.060s
user    0m0.000s
sys     0m0.015s

$ time ./old ExitProcess
0000000076f1c120
Segmentation fault

real    0m0.040s
user    0m0.000s
sys     0m0.015s
```

```sh
$ time ./old CtrlRoutine 0 9848

real    0m0.070s
user    0m0.000s
sys     0m0.031s

$ time ./new CtrlRoutine 0 10052

real    0m10.110s
user    0m0.000s
sys     0m0.031s
```

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: ah, trying this in MSYS2 shell for `old.exe` simply closed the shell, but the weird thing is it works in git bash(the above time function were from Git Bash).

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: @dscho Can you help me out so that I can get this PR in?

Comment (dscho) [reply winsup/utils/getprocaddr.c]: I will try to find some time, but this week I'm a bit short on it.

**Comment by agorgl** [comment]
Waiting for this eagerly!

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Maybe I think we can rename the executable and not worry about this much?

Comment (dscho) [reply winsup/utils/getprocaddr.c]: I don't think we can move forward on this before we understand the root cause for those 7 seconds.

Comment (dscho) [reply winsup/utils/getprocaddr.c]: For the record, I just compiled this and I do not see those seven seconds.

However, what I _do_ notice is that my _entire_ `tmux` session is _GONE_ when I run `getprocaddr64.exe CtrlRoutine`.

That suggests to me that my advice to put back that `--alloc-console` logic for the `CtrlRoutine` part was spot on. It is absolutely required. Without it you will annoy users, just like it annoyed me when not only the current terminal but all 17 tmux panes vanished without a trace.

Comment (dscho) [reply winsup/utils/getprocaddr.c]: When reinstating the `--alloc-console` logic (although implicitly, when `CtrlRoutine` was asked for), I really don't see those 7 (or 10) seconds at all. And I don't see that segmentation fault, either:

```
$ time ./x86_64-pc-msys/winsup/utils/getprocaddr64.exe CtrlRoutine
00007ff8cf91b340

real    0m0.251s
user    0m0.000s
sys     0m0.046s

$ time ./x86_64-pc-msys/winsup/utils/getprocaddr64.exe CtrlRoutine
00007ff8cf91b340

real    0m0.231s
user    0m0.000s
sys     0m0.015s

$ time ./x86_64-pc-msys/winsup/utils/getprocaddr64.exe TerminateProcess
00007ff8d0d20760

real    0m0.103s
user    0m0.000s
sys     0m0.062s

$ time ./x86_64-pc-msys/winsup/utils/getprocaddr64.exe TerminateProcess
00007ff8d0d20760

real    0m0.139s
user    0m0.015s
sys     0m0.062s
```

As you can see, `CtrlRoutine` is slower than `TerminateProcess`, but that's probably to be expected.

I _could_ imagine that you are seeing a 7 second penalty because of some anti-malware that gets suspicious about the stack tracing.

For the record, I reinstated the `--alloc-console` logic thusly:

```diff
diff --git a/winsup/utils/getprocaddr.c b/winsup/utils/getprocaddr.c
index 0fa07827ec..54c252d934 100644
--- a/winsup/utils/getprocaddr.c
+++ b/winsup/utils/getprocaddr.c
@@ -179,6 +179,18 @@ int main(int argc, char **argv)
         return 1;
     }
 
+    /* Avoid terminating all processes attached to the current console */
+    if (!FreeConsole () && GetLastError () != ERROR_INVALID_PARAMETER)
+      {
+        output (1, "Could not detach from current Console: %d\n", (int)GetLastError());
+	return 1;
+      }
+    if (!AllocConsole ())
+      {
+        output (1, "Could not allocate a new Console\n");
+	return 1;
+      }
+
     if (!SetConsoleCtrlHandler(ctrl_handler, TRUE))
     {
         output(1, "Could not register Ctrl handler\n");
```

Comment (dscho) [reply winsup/utils/getprocaddr.c]: On further thought, that comment should probably be a bit more verbose. Something like this:

```c
    /*
     * Avoid terminating all processes attached to the current console;
     * This would happen if we used the same console as the caller, though,
     * because we are sending a CtrlEvent on purpose (which _is_ sent to
     * all processes connected to the same console, and the other processes
     * are most likely unprepared for that CTRL_BREAK_EVENT and would be
     * terminated as a consequence, _including the caller_).
     */
```

File: winsup/utils/getprocaddr.c [hunk 16]
```diff
@@ -0,0 +1,198 @@
...
+  CloseHandle(GetStdHandle(STD_OUTPUT_HANDLE));
+  SymCleanup(process);
+
+  exit(0);
+}
+
+int main(int argc, char **argv)
+{
+    char *end;
+    if (argc != 2 && argc < 4)
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: I doubt that `argc < 4` is the correct check here. What we want is to verify that either 2 or 4 arguments are there. Therefore the condition should read thusly:

```suggestion
    if (argc != 2 && argc != 4)
```

This would also prevent those two (identical, hence disagreeing with the DRY principle) `if (argc > 4)` blocks below.

File: winsup/utils/getprocaddr.c [hunk 17]
```diff
@@ -0,0 +1,198 @@
...
+
+  if (!SymFromAddrW (process, (DWORD64)(intptr_t)address, &displacement, info))
+    {
+      output (1, "Could not get symbol info\n");
+      SymCleanup(process);
+      return FALSE;
+    }
+
+  if (do_print_address)
+  {
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: When adding code, it is always good to imitate the coding style of the surrounding code. It's like the saying "When in Rome, do as the Romans do".

In this instance, the curly brace should be indented two more spaces than the preceding `if` statement.

(For the record, I dislike the GNU coding convention, but my taste does not matter at all when I contribute to Cygwin, it matters more that the coding style is consistent because it would otherwise be disruptive to the reader, which includes future me.)

File: winsup/utils/getprocaddr.c [hunk 18]
```diff
@@ -0,0 +1,198 @@
...
+  }
+  else
+  {
+    HANDLE main_process = OpenProcess(PROCESS_CREATE_THREAD |
+                                          PROCESS_QUERY_INFORMATION |
+                                          PROCESS_VM_OPERATION | PROCESS_VM_WRITE |
+                                          PROCESS_VM_READ,
+                                      FALSE, pid);
+    if (main_process == NULL)
+      return 1;
```
Comment (dscho) [inline winsup/utils/getprocaddr.c:136]: Should we print an error message here?

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 19]
```diff
@@ -0,0 +1,281 @@
...
+#include <tlhelp32.h>
+#include <unistd.h>
+
+/**
+ * Terminates the process corresponding to the process ID and all of its
+ * directly and indirectly spawned subprocesses using the
+ * exit_one_process() function.
+ */
+static int
+exit_process_tree(HANDLE main_process, int exit_code)
```
Comment (dscho) [inline winsup/cygwin/include/cygwin/exit_process.h]: The idea of `exit_process_tree()` is this: contrary to POSIX' `kill()` (at least with certain signals), `TerminateProcess()` does not leave the killed processes _any_ way to call `atexit()`-registered handlers. But those would be the ones that kill child processes. Hence we need to enumerate the process tree and terminate the children, too.

However, sending a CtrlEvent is different: it _does_ allow `atexit()`-registered handlers to run.

Therefore, I would contend that we should not even call `exit_process_tree()` by default, but something like `exit_process()` (which either sends a CtrlEvent to the specified process or injects `ExitProcess()`, and that process _only_, or terminates the process tree only if `TerminateProcess()` is used).

File: winsup/utils/getprocaddr.c [hunk 20]
```diff
@@ -0,0 +1,198 @@
+#include <stdio.h>
+#include <windows.h>
+
+/**
+ * To determine the address of kernel32!CtrlRoutine, we need to use
+ * dbghelp.dll. But we want to avoid linking statically to that library because
+ * the normal operation of cygwin-console-helper.exe (i.e. to allocate a hidden
+ * Console) does not need it.
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: This comment is now super stale. Likewise the next paragraph.

File: winsup/utils/getprocaddr.c [hunk 21]
```diff
@@ -0,0 +1,198 @@
...
+ *
+ * Therefore, we declare the SYMBOL_INFOW structure here, load the dbghelp
+ * library via LoadLibraryExA() and obtain the SymInitialize(), SymFromAddrW()
+ * and SymCleanup() functions via GetProcAddr().
+ * 
+ * After that a remote thread is injected into that process
+ * to send the exit code.
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: This is only _optional_.

File: winsup/utils/getprocaddr.c [hunk 22]
```diff
@@ -0,0 +1,198 @@
...
+ */
+
+#include <dbghelp.h>
+
+static int pid;
+static uintptr_t exit_code;
+static BOOL do_print_address;
+
+/* Avoid fprintf(), as it would try to reference '__getreent' */
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: Is this still true?

File: winsup/utils/getprocaddr.c [hunk 23]
```diff
@@ -0,0 +1,198 @@
...
+    if (WaitForSingleObject(thread, 10000) == WAIT_OBJECT_0)
+      res = 0;
+    CloseHandle(thread);
+  }
+
+  return res;
+}
+
+static WINAPI BOOL
+ctrl_handler(DWORD ctrl_type)
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: I think this function makes for a fine spot to add a multi-line comment describing the strategy where we send a CtrlEvent to the current process for the _sole_ purpose of capturing the address of the `CtrlRoutine` function, by looking at the stack trace. This description should stress that we would _love_ to use `GetProcAddress()` as we do for `ExitProcess()`, but sadly `CtrlRoutine` is not exported (although the `.pdb` files ensure that we can see it in a debugger).

File: winsup/utils/getprocaddr.c [hunk 24]
```diff
@@ -0,0 +1,198 @@
...
+ * 
+ * After that a remote thread is injected into that process
+ * to send the exit code.
+ */
+
+#include <dbghelp.h>
+
+static int pid;
+static uintptr_t exit_code;
+static BOOL do_print_address;
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: Why do we need both `do_print_address` _and_ `pid`? Since `pid` is an `int` (shouldn't it be a `DWORD`? [`GetProcessId()`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getprocessid) returns a `DWORD`...), we could simply treat `pid == 0` as an indicator that we want to print the address. After all, the process with pid 0 should never be terminated, except on shutdown.

File: winsup/utils/getprocaddr.c [hunk 25]
```diff
@@ -0,0 +1,198 @@
...
+    {
+        exit_code = atoi(argv[2]);
+        pid = strtoul(argv[3], NULL, 0);
+    }
+    if (argc == 2)
+    {
+        do_print_address = TRUE;
+    }
+
+    if (strcmp(argv[1], "CtrlRoutine"))
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: This would be a fine place to say that the easy route is to use `GetProcAddress()` (and that this route is unfortunately not viable for `CtrlRoutine` because that symbol is not exported).

File: winsup/utils/getprocaddr.c [hunk 26]
```diff
@@ -0,0 +1,198 @@
...
+    if (!GenerateConsoleCtrlEvent(CTRL_BREAK_EVENT, 0))
+    {
+        output(1, "Could not simulate Ctrl+Break\n");
+        return 1;
+    }
+
+    /* This is needed for both thread to inject
+    * and GenerateConsoleCtrlEvent.
+    * Gives 1 sec time. */
+    Sleep(1000);
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: I don't like that `Sleep()` at all. It does not say "wait until the event has been processed".

A much better way would most likely be to use a semaphore. In Win32 land, that would entail calling `CreateEvent()`, storing the result in a global variable, calling `SetEvent()` in the `ctrl_handler` after everything is said and done, and calling `WaitForSingleObject()` here. See https://docs.microsoft.com/en-us/windows/win32/sync/using-event-objects for an example (look for `ghWriteEvent`).

File: winsup/cygwin/include/cygwin/exit_process.h (hunk 19 above)
Comment (dscho) [reply winsup/cygwin/include/cygwin/exit_process.h]: And yes, I know, this is my fault because I did not change the name after realizing that the `atexit()`-registered handlers weren't run upon `TerminateProcess()` and looking for a better solution (and finding one, first with injecting `ExitProcess()`, and then even injecting `CtrlRoutine()`).

**Comment by dscho** [comment]
> 
> 
> @dscho Is there anything else I should do here for this to be merged?

@naveen521kk please do not mistake my lack of engagement as a sign that I am uninterested. The contrary is true! I'm just busy elsewhere, and I am incredibly grateful that you are driving this here initiative.

From my perspective, the PR is on its way to a shape that can be merged. There are definitely a couple of rough edges (I left a couple remarks hopefully helping to address at least some of those rough edges), and the commit topology will need to see an interactive rebase before it can tell a coherent and engaging story. I am really eager to see it getting there!

If any of my comments are unclear, please do not hesitate at all to ask me to clarify.

Also, if you're interested in pairing on this project, I can probably carve out some time at some stage, just let me know if you would like that.

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: First, using the logic which uses `AllocConsole` means it going to create a popup, there was no way to customize that directly, as in the docs https://docs.microsoft.com/en-us/windows/console/allocconsole. It does create a popup when I compile and run with your patch... It doesn't look good to have a popup on pressing Ctrl+C sadly.

So, on reading https://docs.microsoft.com/en-us/windows/console/creation-of-a-console, it seems we can launch a `cmd` using `CreateProcess` and attach to it using [`AttachConsole`](https://docs.microsoft.com/en-us/windows/console/attachconsole). My patch, which I previously linked does it, but it fails somewhere. I can look into fixing it though. And, that was the reason I was seeing some extra seconds. I can possibly fix them.

Next, about SegFaults, it happens only when it print's something say a help message. For example, this happens.
```sh
$ ./getprocaddr.exe
Need a function name, exit code and pid
Segmentation fault
```

File: winsup/utils/getprocaddr.c (hunk 17 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Fine. I was doing this like "code first, make it work, style last", so I would format them accordingly after everything is working.

File: winsup/utils/getprocaddr.c (hunk 22 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: No idea...

File: winsup/utils/getprocaddr.c (hunk 26 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Looks good, I will give it a try later today.

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (dscho) [reply winsup/utils/getprocaddr.c]: > It does create a popup when I compile and run with your patch... It doesn't look good to have a popup on pressing Ctrl+C sadly.

Don't we already call `CreateProcessW()` with the console hidden?

*clicketyclick*

Yes we do: https://github.com/msys2/msys2-runtime/pull/31/files#diff-083ad673bed6c3e0d175243e2aa51f3c5ea6576894e2cd06b8c78f654f5da4a1R92

We even make sure to open a new process group (which I _think_ means that it creates a new console).

To make sure, we could guard [the code I mentioned above](https://github.com/msys2/msys2-runtime/pull/31#discussion_r635588030) behind a check that calls [`GetConsoleProcessList()`](https://docs.microsoft.com/en-us/windows/console/getconsoleprocesslist) and only attaches a new console if that function returned something larger than 1 (because that means that not only the current process is attached to the current console, but other processes, too).

I don't think we should call `cmd.exe` just to avoid a console from popping up, ever ;-)

Comment (dscho) [reply winsup/utils/getprocaddr.c]: > about SegFaults, it happens only when it print's something say a help message. For example, this happens.
> 
> ```shell
> $ ./getprocaddr.exe
> Need a function name, exit code and pid
> Segmentation fault
> ```

Have you tried running it in `gdb` to figure out where that segmentation fault is coming from?

File: winsup/utils/getprocaddr.c (hunk 22 above)
Comment (dscho) [reply winsup/utils/getprocaddr.c]: Could I ask you to replace that `WriteFile()` dance by an `fprintf()` and see whether the program links fine? If it does, then you don't need that super ugly `output()` function anymore.

File: winsup/utils/getprocaddr.c (hunk 17 above)
Comment (dscho) [reply winsup/utils/getprocaddr.c]: Style fixes are _the worst_ when you have to perform an interactive rebase. They cause not only merge conflicts when moving the style fix to the correct commit, no, _another_ merge conflict (at _least_ one, that is) will happen when the incorrect style is expected in later commits' diff context.

If you plan on cleaning this up, the sooner you do, the less hassle it will be.

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: > Have you tried running it in gdb to figure out where that segmentation fault is coming from?

I have, but strangely it doesn't segfault there :thinking: 
```sh
(gdb) run
Starting program: H:\mingw\test_programs\newgdb\getprocaddr.exe
Need a function name, exit code and pid
Or needs a function name.
[Inferior 1 (process 7460) exited with code 01]
```
Maybe it is something with output handles, not sure.

> I don't think we should call cmd.exe just to avoid a console from popping up, ever ;-)

OK, I was doing that, and that's why those 6-7 seconds :facepalm: 

> Don't we already call CreateProcessW() with the console hidden?

So, that means we will not get a popup when it is called from runtime itself?
I think for creating a new console `CREATE_NEW_CONSOLE` flag should be passed. https://docs.microsoft.com/en-us/windows/win32/procthread/process-creation-flags#flags

> To make sure, we could guard the code I mentioned above behind a check that calls GetConsoleProcessList() and only attaches a new console if that function returned something larger than 1 (because that means that not only the current process is attached to the current console, but other processes, too).

That looks good. If it called from runtime we don't need to create a console, if it is from a normal terminal we should, right?

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Edit about gdb: I used `winpty` to run `gdb` which is why I didn't get SegFault there. (it gives nice colours there, you know?)

When running plainly `gdb` in MSYS2 console, I get
```sh
(gdb) run
Starting program: H:\mingw\test_programs\newgdb\getprocaddr.exe
Need a function name, exit code and pid

Program received signal SIGSEGV, Segmentation fault.
0x000007fefd061b44 in WriteFile () from C:\Windows\system32\KernelBase.dll
(gdb) backtrace
#0  0x000007fefd061b44 in WriteFile () from C:\Windows\system32\KernelBase.dll
#1  0x00000000773c1b06 in WriteFile () from C:\Windows\system32\kernel32.dll
#2  0x000000013fc41635 in output (error=1,
    fmt=0x13fc4a0b8 "Need a function name, exit code and pid\n")
    at getprocaddr.c:37
#3  0x000000013fc41a86 in main (argc=1, argv=0x6b82b0) at getprocaddr.c:179
```

File: winsup/utils/getprocaddr.c (hunk 17 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Oh right, I will clean them up soon.

File: winsup/utils/getprocaddr.c (hunk 22 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: I did something like
```patch
diff --git a/winsup/utils/getprocaddr.c b/winsup/utils/getprocaddr.c
index 0fa07827e..133c0bbfb 100644
--- a/winsup/utils/getprocaddr.c
+++ b/winsup/utils/getprocaddr.c
@@ -32,7 +32,7 @@ output (BOOL error, const char *fmt, ...)
   vsnprintf (buffer, sizeof(buffer) - 1, fmt, ap);
   buffer[sizeof(buffer) - 1] = '\0';
   va_end (ap);
-  WriteFile (GetStdHandle(error ? STD_ERROR_HANDLE : STD_OUTPUT_HANDLE),
+  fprintf (error ? stderr : stdout,
              buffer, strlen (buffer), NULL, NULL);
 }
```
and it seems to work, also without any SegFaults.

File: winsup/utils/getprocaddr.c (hunk 17 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Is there a style guide somewhere for this project? I am, slightly unfamiliar with that.
( Also, this is a side-effect of vscode automatically formatting things, if it can be automatically formatted it would be better)

**Comment by naveen521kk** [comment]
I will get over this today, possibly.

File: winsup/utils/getprocaddr.c (hunk 17 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Found there was an option in vscode to add GNU format, and it sort of works good.

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: OK fixed it with a force push.

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Ok, this is done in https://github.com/msys2/msys2-runtime/pull/31/commits/ee97ce904f8a09960eb5a6904b2e1e2312d82e04

and it seems to work well, if called from console creates a popup, if called from runtime simply executes. Thanks for your help.

File: winsup/utils/getprocaddr.c (hunk 18 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c:136]: Done in https://github.com/msys2/msys2-runtime/pull/31/commits/4892b6cf4626d32b28d27387e2eccb851532f832

File: winsup/utils/getprocaddr.c (hunk 21 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Updated https://github.com/msys2/msys2-runtime/pull/31/commits/8e00f73dd4b43e218316faf604ffd001f3c7e4bf

File: winsup/utils/getprocaddr.c (hunk 20 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Updated https://github.com/msys2/msys2-runtime/pull/31/commits/8e00f73dd4b43e218316faf604ffd001f3c7e4bf

File: winsup/utils/getprocaddr.c (hunk 22 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: ah, this does output the pointer. no idea why.

File: winsup/utils/getprocaddr.c (hunk 24 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Ok removed https://github.com/msys2/msys2-runtime/pull/31/commits/026df76554c00d6241d1f691a257755389283208.

File: winsup/utils/getprocaddr.c (hunk 22 above)
Comment (dscho) [reply winsup/utils/getprocaddr.c]: Could you help me understand what you mean by "the pointer"?

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: I mean, when doing 
```sh
$ ./getprocaddr CtrlRoutine
0000000077b54810
Segmentation fault
```
the character prints, I meant that as the pointer. When I try the same with that patch it doesn't print anything.

With this patch I linked in https://github.com/msys2/msys2-runtime/pull/31#discussion_r636109929, it doesn't print the pointer, that character.
```sh
$ ./getprocaddr CtrlRoutine

```
Maybe because of the new console creation.

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (dscho) [reply winsup/utils/getprocaddr.c]: > > Don't we already call CreateProcessW() with the console hidden?
> 
> So, that means we will not get a popup when it is called from runtime itself?

Exactly.

> I think for creating a new console `CREATE_NEW_CONSOLE` flag should be passed. https://docs.microsoft.com/en-us/windows/win32/procthread/process-creation-flags#flags

I think we do need CREATE_NEW_PROCESS_GROUP, quoting part from [here](https://docs.microsoft.com/en-us/windows/win32/procthread/process-creation-flags#flags):

> Process groups are used by the GenerateConsoleCtrlEvent function to enable sending a CTRL+BREAK signal to a group of console processes.

That sounds like exactly what we want.

> I used `winpty` to run `gdb` which is why I didn't get SegFault there. (it gives nice colours there, you know?)

Yes, I did know about `winpty`, it also fixes the <kbd>Tab</kbd> handling when you use the MINGW version of `gdb`. I use it all the time.

> When running plainly `gdb` in MSYS2 console, I get
> 
> ```shell
> (gdb) run
> Starting program: H:\mingw\test_programs\newgdb\getprocaddr.exe
> Need a function name, exit code and pid
> 
> Program received signal SIGSEGV, Segmentation fault.
> 0x000007fefd061b44 in WriteFile () from C:\Windows\system32\KernelBase.dll
> (gdb) backtrace
> #0  0x000007fefd061b44 in WriteFile () from C:\Windows\system32\KernelBase.dll
> #1  0x00000000773c1b06 in WriteFile () from C:\Windows\system32\kernel32.dll
> #2  0x000000013fc41635 in output (error=1,
>     fmt=0x13fc4a0b8 "Need a function name, exit code and pid\n")
>     at getprocaddr.c:37
> #3  0x000000013fc41a86 in main (argc=1, argv=0x6b82b0) at getprocaddr.c:179
> ```

What a bummer. That still does tell me what is going wrong, but it does suggest that we should switch from using `output()` directly to `printf()` for `output(0, ...)` calls, and to `fprintf(stderr, ...)` for `output(1, ...)` calls.

> Ok, this is done in [ee97ce9](https://github.com/msys2/msys2-runtime/commit/ee97ce904f8a09960eb5a6904b2e1e2312d82e04)

👍 

> and it seems to work well, if called from console creates a popup, if called from runtime simply executes. Thanks for your help.

If you want to avoid that popup, you could probably use `IsWindowVisible(GetConsoleWindow())` to check whether the current console window is shown, and re-execute (using `_wpgmptr` as `lpApplicationName` and `GetCommandLineW()` as `lpCommandLine` in a `CreateProcessW()` call, and of course setting the flags so that the console window is hidden).

I am not really sure this is worth the effort, though, because this is an executable _meant_ to be called from the MSYS2 runtime, after all.

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 27]
```diff
@@ -0,0 +1,281 @@
...
+  if (!x)
+    {
+      CloseHandle(h[0]);
+      return NULL;
+    } else {
+    /* Wait for the process to complete for 10 seconds */
+      WaitForSingleObject(pi.hProcess, 10000 );
+    }
+
+  if (!GetExitCodeProcess(pi.hProcess, process_exit))
```
Comment (dscho) [inline winsup/cygwin/include/cygwin/exit_process.h]: This would pass an uninitialized pointer to `GetExitCodeProcess()`: `process_exit` is supposed to be a pointer to a local variable of type `DWORD`, which will be assigned the exit code (or `STILL_ACTIVE`). Please compare to https://github.com/git-for-windows/msys2-runtime/blob/12e88192b84673b81c6550e48fb7df9b607dada3/winsup/cygwin/include/cygwin/exit_process.h#L359

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 28]
```diff
@@ -0,0 +1,281 @@
...
+
+#include <wchar.h>
+#include <math.h>
+
+#ifndef __INSIDE_CYGWIN__
+/* To help debugging via kill.exe */
+#define small_printf(...) fprintf(stderr, __VA_ARGS__)
+#endif
+
+static LPDWORD
```
Comment (dscho) [inline winsup/cygwin/include/cygwin/exit_process.h]: The return type should probably be `BOOL`: `TRUE` if we managed to send the signal, `FALSE` if we failed.

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 29]
```diff
@@ -0,0 +1,281 @@
...
+  if (cygwin_conv_path (CCP_POSIX_TO_WIN_W, name, wbuf, PATH_MAX) ||
+      GetFileAttributesW (wbuf) == INVALID_FILE_ATTRIBUTES)
+    return NULL;
+
+  HANDLE h[2];
+  SECURITY_ATTRIBUTES attrs;
+  attrs.nLength = sizeof(attrs);
+  attrs.bInheritHandle = TRUE;
+  attrs.lpSecurityDescriptor = NULL;
+  if (!CreatePipe(&h[0], &h[1], &attrs, 0))
```
Comment (dscho) [inline winsup/cygwin/include/cygwin/exit_process.h]: Since we no longer read back the function address, we do not need this pipe anymore, I think.

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: > I think we do need CREATE_NEW_PROCESS_GROUP, quoting part from here:

:+1: 

> What a bummer. That still does tell me what is going wrong, but it does suggest that we should switch from using output() directly to printf() for output(0, ...) calls, and to fprintf(stderr, ...) for output(1, ...) calls.

I still think, "the pointer"(as explained [here](https://github.com/msys2/msys2-runtime/pull/31#discussion_r636942164)) doesn't print when using `fprintf`, so we should use this output function there.

> I am not really sure this is worth the effort, though, because this is an executable meant to be called from the MSYS2 runtime, after all.

yes, so we don't need to worry about that.

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 30]
```diff
@@ -0,0 +1,281 @@
...
+  swprintf (cmd, len + 1, L"%S %S %d %ld", wbuf, function_name, exit_code, pid);
+
+  si.cb = sizeof (si);
+  si.dwFlags = STARTF_USESHOWWINDOW | STARTF_USESTDHANDLES;
+  si.wShowWindow = SW_HIDE;
+  si.lpTitle = title;
+  si.hStdInput = si.hStdError = si.hStdOutput = INVALID_HANDLE_VALUE;
+
+  /* Create a new hidden process. */
+  BOOL x = CreateProcessW (NULL, cmd, NULL, NULL, TRUE,
```
Comment (dscho) [inline winsup/cygwin/include/cygwin/exit_process.h]: I don't think we need to do anything except `return FALSE` if `CreateProcessW()` returns `FALSE`. Therefore, we probably do not even need this `x` variable (otherwise we would want a better name, though).

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 31]
```diff
@@ -0,0 +1,281 @@
...
+  LPTHREAD_START_ROUTINE address = NULL;
+  int signo = exit_code & 0x7f;
+  BOOL is_wow;
+  int bitness;
+  switch (signo)
+  {
+  case SIGINT:
+  case SIGQUIT:
+    if (get_wow(process, is_wow, bitness) &&
+        0 /* exit code 0 = success */ == kill_via_console_helper(bitness, L"CtrlRoutine",
```
Comment (dscho) [inline winsup/cygwin/include/cygwin/exit_process.h]: If we change the return value type of `kill_via_console_helper()` to `BOOL`, we can save a ton of indentation here.

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 32]
```diff
@@ -0,0 +1,281 @@
...
+                                                                 signo == SIGINT ? CTRL_C_EVENT : CTRL_BREAK_EVENT, pid))
+      return 0;
+    /* fall-through */
+  case SIGTERM:
+    if (get_wow(process, is_wow, bitness) &&
```
Comment (dscho) [inline winsup/cygwin/include/cygwin/exit_process.h]: We probably should fold `get_wow()` into `kill_via_console_helper()`: this would also make the code a bit more thread-safe, in case we want to signal two processes concurrently (a `static int is_32_bit_process` is a single instance per process).

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 33]
```diff
@@ -0,0 +1,281 @@
...
+	   */
+          for (i = len - 1; i >= 0; i--)
+            {
+              if (pids[i] == entry.th32ProcessID)
+                break;
+              if (pids[i] != entry.th32ParentProcessID)
+	        continue;
+
+              /* We found a process to kill; is it an MSYS2 process? */
+	      pid_t cyg_pid = cygwin_winpid_to_pid(entry.th32ProcessID);
```
Comment (dscho) [inline winsup/cygwin/include/cygwin/exit_process.h]: This line has funny indentation.

File: winsup/cygwin/include/cygwin/exit_process.h (hunk 19 above)
Comment (dscho) [reply winsup/cygwin/include/cygwin/exit_process.h]: I guess the solution is actually to turn things around, letting `exit_process_tree()` call `TerminateProcess()` instead of `exit_one_process()` (and losing the `int exit_code` parameter). Then, renaming `exit_one_process()` to `exit_process()`, and calling `exit_process_tree()` instead of `TerminateProcess()` when falling back.

File: winsup/utils/getprocaddr.c (hunk 22 above)
Comment (dscho) [reply winsup/utils/getprocaddr.c]: Oh.

In any case, I think we can totally side-step this problem by using `printf()` and `fprintf()` directly.

File: winsup/utils/kill.cc [hunk 34]
```diff
@@ -186,10 +187,20 @@ forcekill (pid_t pid, DWORD winpid, int sig, int wait)
...
+      if (DuplicateHandle (cur, h, cur, &h2, PROCESS_CREATE_THREAD |
+			      PROCESS_QUERY_INFORMATION |
+			      PROCESS_VM_OPERATION |
+			      PROCESS_VM_WRITE | PROCESS_VM_READ |
+			      PROCESS_TERMINATE, FALSE, 0))
+      {
+        CloseHandle(h);
+        h = h2;
+      }
+      exit_process_tree (h2, 128 + sig);
```
Comment (dscho) [inline winsup/utils/kill.cc:202]: If you go along with my [suggestion above](https://github.com/msys2/msys2-runtime/pull/31/files#r636963217), this will also need to be changed to `exit_process(h2, 128 + sig)`.

**Comment by dscho** [comment]
@naveen521kk please do not let my continued suggestions discourage you, I am really excited how far you've come. It will soon be time to use the interactive rebase to structure this PR into a small "story" (because we will have to forward-port these patches to every new Cygwin version, it does not make sense to keep the historical record how the changes came about, but to have a concise patch series instead that is easy to forward-port). I'd like to suggest keeping with my original structure:

1. Add a helper to obtain a function's address in kernel32.dll
2. Emulate GenerateConsoleCtrlEvent() upon Ctrl+C 
3. kill: kill Win32 processes more gently

If you think it improves readability (and/or makes it easier to resolve merge conflicts in the future), you could insert the change that teaches `getprocaddr` to inject a remote thread, probably between patch 1 and patch 2. Otherwise I would just squash it into 1.

Great progress!

File: winsup/utils/getprocaddr.c (hunk 22 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: I think we can use `printf` and `fprintf` wherever possible and let the `output` function only for the pointer.

File: winsup/utils/getprocaddr.c (hunk 23 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Done in https://github.com/msys2/msys2-runtime/pull/31/commits/9489d1ad2401b33cf1b9d881329fbb2a76f4945c

File: winsup/utils/getprocaddr.c (hunk 25 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Done in https://github.com/msys2/msys2-runtime/pull/31/commits/9489d1ad2401b33cf1b9d881329fbb2a76f4945c

File: winsup/utils/getprocaddr.c (hunk 26 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Ok done, https://github.com/msys2/msys2-runtime/pull/31/commits/29960882133de6aea3d350899eda9a182a8e2901

Can you check does that look good?

File: winsup/utils/getprocaddr.c [hunk 35]
```diff
@@ -8,12 +8,15 @@
  * printed if asked to, or an remote thread is injected.
  */
 
-#include <dbghelp.h>
 #include <stdio.h>
 #include <windows.h>
 
+/* Include dbg help after window.h*/
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: window.h misses an "s". ;-)

File: winsup/utils/getprocaddr.c (hunk 22 above)
Comment (dscho) [reply winsup/utils/getprocaddr.c]: We do not need `output()` for the pointer, we can easily call `printf("%p", address)`.

File: winsup/utils/getprocaddr.c [hunk 36]
```diff
@@ -128,7 +131,11 @@ ctrl_handler (DWORD ctrl_type)
     }
   CloseHandle (GetStdHandle (STD_OUTPUT_HANDLE));
   SymCleanup (process);
-
+  if (!SetEvent (CtrlEvent))
+    {
+      output (1, "SetEvent failed (%d)\n", GetLastError ());
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: `s/output (1, /fprintf (stderr, /` ;-)

File: winsup/utils/getprocaddr.c [hunk 37]
```diff
@@ -231,9 +238,29 @@ main (int argc, char **argv)
...
+    {
+    // All thread objects were signaled
+    case WAIT_OBJECT_0:
+      break;
+
+    // An error occurred
+    default:
+      output (1, "WaitForSingleObject failed (%d)\n", GetLastError ());
+      return 1;
+    }
```
Comment (dscho) [inline winsup/utils/getprocaddr.c:263]: Wouldn't this be much easier to read as `if (WaitResult != WAIT_OBJECT_0) { fprintf(stderr, ...); return 1; }`?

File: winsup/utils/getprocaddr.c [hunk 38]
```diff
@@ -231,9 +238,29 @@ main (int argc, char **argv)
...
+                           FALSE,             // initial state is nonsignaled
+                           TEXT ("CtrlEvent") // object name
+  );
+  if (CtrlEvent == NULL)
+    {
+      output (1, "CreateEvent failed (%d)\n", GetLastError ());
+      return 1;
+    }
+
+  DWORD WaitResult = WaitForSingleObject (CtrlEvent, 10000 /* 10 seconds*/);
```
Comment (dscho) [inline winsup/utils/getprocaddr.c]: Since the `WaitResult` is used immediately and only once, why not move the call to `WaitForSingleObject()` into the conditional directly?

File: winsup/utils/getprocaddr.c (hunk 22 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: I wonder whether it will get printed correctly after we have shifted to a new console(using `AllocConsole`), but maybe I will try that and then see.

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: As I expected, the pointer doesn't print in the original console, rather it prints on the popup and then exits. Atleast, when using `output()` it printed on the original console on the MSYS shell (on cmd it never printed in the original shell.).

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: I did https://github.com/msys2/msys2-runtime/pull/31/commits/b1c94c16f33267df692b776c4797a2e93ff96b32, with that the pointer for `CtrlRoutine` doesn't print while `ExitProcess` prints.

File: winsup/cygwin/include/cygwin/exit_process.h (hunk 19 above)
Comment (naveen521kk) [reply winsup/cygwin/include/cygwin/exit_process.h]: > and losing the `int exit_code` parameter

what should be passed to `TerminateProcess` then?

Comment (naveen521kk) [reply winsup/cygwin/include/cygwin/exit_process.h]: Does https://github.com/msys2/msys2-runtime/pull/31/commits/efc36e4202b8a62acb1183e888b5aafb70f6bade look good?

File: winsup/cygwin/include/cygwin/exit_process.h (hunk 33 above)
Comment (naveen521kk) [reply winsup/cygwin/include/cygwin/exit_process.h]: I think I am going to run this file through clang-format, since this file is something we created and shouldn't create any problems with upstream.

File: winsup/cygwin/include/cygwin/exit_process.h (hunk 27 above)
Comment (naveen521kk) [reply winsup/cygwin/include/cygwin/exit_process.h]: Done https://github.com/msys2/msys2-runtime/pull/31/commits/8f1df8bed5df531adbc70fa1eeadb212185d35c5

File: winsup/cygwin/include/cygwin/exit_process.h (hunk 28 above)
Comment (naveen521kk) [reply winsup/cygwin/include/cygwin/exit_process.h]: Ok. https://github.com/msys2/msys2-runtime/pull/31/commits/7ef8dd0e931e35f556d0dd2a7ea0c99d58823c03

File: winsup/cygwin/include/cygwin/exit_process.h (hunk 29 above)
Comment (naveen521kk) [reply winsup/cygwin/include/cygwin/exit_process.h]: Done https://github.com/msys2/msys2-runtime/pull/31/commits/733723814e9c96dde678eca206283469b00f171c

File: winsup/cygwin/include/cygwin/exit_process.h (hunk 30 above)
Comment (naveen521kk) [reply winsup/cygwin/include/cygwin/exit_process.h]: Done. https://github.com/msys2/msys2-runtime/pull/31/commits/df0c178f4d96d929f5b1a5d958f3e0a58074fe2e

File: winsup/cygwin/include/cygwin/exit_process.h (hunk 32 above)
Comment (naveen521kk) [reply winsup/cygwin/include/cygwin/exit_process.h]: Done https://github.com/msys2/msys2-runtime/pull/31/commits/e83163802298b9bf256ac437a8c325a28c1625b5

**Comment by naveen521kk** [comment]
Looks like pretty much everything is resolved except https://github.com/msys2/msys2-runtime/pull/31#discussion_r635596118 and https://github.com/msys2/msys2-runtime/pull/31#discussion_r635595032. I should try testing this.

**Comment by jeremyd2019** [comment]
I hate to throw a wrench into this already complicated PR, but have you seen [IsWow64Process2](https://docs.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process2)?  The old assumption that processes are either 32-bit x86 or 64-bit x86_64 no longer holds.  ARM64 can be ARM64 ARM32 or x86 32, and with insider preview builds x86_64 is added too.  If you're trying to figure out non-cygwin processes they could be any of those.

After https://github.com/msys2/msys2-runtime/commit/d77a022baf5b1f6e8ce7f04ce294a60df1d13519 it is available to call (I don't know if you've rebased lately).  I don't know if you can deal with all of these, but should at least fail gracefully in those cases.

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 39]
```diff
@@ -49,9 +49,13 @@
 #endif
 
 static BOOL
-kill_via_console_helper (int bitness, wchar_t *function_name, int exit_code,
+kill_via_console_helper (HANDLE process, wchar_t *function_name, int exit_code,
                          DWORD pid)
 {
+  BOOL is_wow;
+  int bitness;
+  get_wow (process, is_wow, bitness);
```
Comment (jeremyd2019) [inline winsup/cygwin/include/cygwin/exit_process.h]: You should check the return value of get_wow I think

Comment (naveen521kk) [reply winsup/cygwin/include/cygwin/exit_process.h]: Yes, if that fails this function shouldn't run, missed that.

Comment (naveen521kk) [reply winsup/cygwin/include/cygwin/exit_process.h]: Done, https://github.com/msys2/msys2-runtime/pull/31/commits/099ee047406d7072d7e46c03939cd3cf9a9137d5

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 40]
```diff
@@ -0,0 +1,277 @@
...
+static int is_32_bit_os = -1;
+
+static BOOL
+get_wow (HANDLE process, BOOL &is_wow, int &bitness)
+{
+  if (is_32_bit_os == -1)
+    {
+      SYSTEM_INFO info;
+
+      GetNativeSystemInfo (&info);
```
Comment (jeremyd2019) [inline winsup/cygwin/include/cygwin/exit_process.h:125]: I think this will lie to you on ARM64.  So sayeth [MSDN](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getnativesysteminfo):
> If the function is called from a 64-bit application, or on a 64-bit system that does not have an Intel64 or x64 processor (such as ARM64), it is equivalent to the GetSystemInfo function.

This is why I mentioned IsWow64Process2, but that's only present on relatively recent Win10.  The autoload stuff would make the function return FALSE and SetLastError to `ERROR_PROC_NOT_FOUND`, so if you cleared the last error, tried calling IsWow64Process2, saw it returned false, and last error was `ERROR_PROC_NOT_FOUND` you could fall back to this method of trying to determine.

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (dscho) [reply winsup/utils/getprocaddr.c]: > > What a bummer. That still does tell me what is going wrong, but it does suggest that we should switch from using output() directly to printf() for output(0, ...) calls, and to fprintf(stderr, ...) for output(1, ...) calls.
> 
> I still think, "the pointer"(as explained [here](https://github.com/msys2/msys2-runtime/pull/31#discussion_r636942164)) doesn't print when using `fprintf`, so we should use this output function there.

Oh, you mean that `stderr` and `stdout` now use the allocated console... that makes sense. But then we probably want to document that idea above the `output()` function.

Or (and this would be my preferred solution) we could ensure that the `stderr` and `stdout` are not redirected to the allocated console, via something like this:

```c
  if (GetConsoleProcessList (&proc_lists, 5) > 1)
    {
      HANDLE out = GetStdHandle (STD_OUTPUT_HANDLE);
      HANDLE err = GetStdHandle (STD_ERROR_HANDLE);

      if (!FreeConsole () && GetLastError () != ERROR_INVALID_PARAMETER)
        {
          fprintf (stderr, "Could not detach from current Console: %d\n",
                   (int)GetLastError ());
          return 1;
        }
      if (!AllocConsole ())
        {
          fprintf (stderr, "Could not allocate a new Console\n");
          return 1;
        }
      SetStdHandle (STD_OUTPUT_HANDLE, out);
      SetStdHandle (STD_ERROR_HANDLE, err);
    }
```

(assuming that that works).

File: winsup/utils/getprocaddr.c (hunk 22 above)
Comment (dscho) [reply winsup/utils/getprocaddr.c]: Good point! I hope the `GetStdHandle()`/`SetStdHandle()` dance I described elsewhere will work around that.

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: I will look into it later today.

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: I think that doesn't my patch looks like
```patch
diff --git a/winsup/utils/getprocaddr.c b/winsup/utils/getprocaddr.c
index ed0083c39..cde8bee2b 100644
--- a/winsup/utils/getprocaddr.c
+++ b/winsup/utils/getprocaddr.c
@@ -202,6 +202,9 @@ main (int argc, char **argv)
   DWORD proc_lists;
   if (GetConsoleProcessList (&proc_lists, 5) > 1)
     {
+      HANDLE out = GetStdHandle (STD_OUTPUT_HANDLE);
+      HANDLE err = GetStdHandle (STD_ERROR_HANDLE);
+
       if (!FreeConsole () && GetLastError () != ERROR_INVALID_PARAMETER)
         {
           fprintf (stderr, "Could not detach from current Console: %d\n",
@@ -213,6 +216,8 @@ main (int argc, char **argv)
           fprintf (stderr, "Could not allocate a new Console\n");
           return 1;
         }
+      SetStdHandle (STD_OUTPUT_HANDLE, out);
+      SetStdHandle (STD_ERROR_HANDLE, err);
     }

   if (!SetConsoleCtrlHandler (ctrl_handler, TRUE))
@@ -242,4 +247,5 @@ main (int argc, char **argv)
       fprintf (stderr, "WaitForSingleObject failed (%d)\n", GetLastError ());
       return 1;
     }
+  return 0;
 }
```
and it doesn't print the pointer both on bash and cmd.

File: winsup/cygwin/include/cygwin/exit_process.h (hunk 40 above)
Comment (naveen521kk) [reply winsup/cygwin/include/cygwin/exit_process.h:125]: I think this can be done in a new PR.

**Comment by naveen521kk** [comment]
About https://github.com/msys2/msys2-runtime/pull/31#commitcomment-51199271, I fixed it in https://github.com/msys2/msys2-runtime/pull/31/commits/bad71a9fa90463e27d5f1fd2c82782f68db35b98 and about https://github.com/msys2/msys2-runtime/pull/31#discussion_r637602297 that patch doesn't seem to work. 

If everything looks good I will rebase this PR :)

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Hmm, since the one thing that prints after allocating a new console is just the pointer how about using the same `output` function there?

Comment (dscho) [reply winsup/utils/getprocaddr.c]: I really like the ease of `fprintf()`, so I'd like to make it work _somehow_. I'll look into it later today, if I find the time.

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Ok. I would be busy for the next few days, only after that, I can look into this.

Comment (dscho) [reply winsup/utils/getprocaddr.c]: So... it looks as if I do not actually need that `GetStdHandle()`/`SetStdHandle()` dance, but instead I only need to `fflush (stdout)` (I ran into this issue a couple of times in the past, where the standard handles of non-MSYS2 processes were connected to MSYS2's named pipes which needed _explicit_ flushing, even for `stderr`).

Therefore, this diff works for me:

```diff
diff --git a/winsup/utils/getprocaddr.c b/winsup/utils/getprocaddr.c
index bddad7004f..6783bc59ad 100644
--- a/winsup/utils/getprocaddr.c
+++ b/winsup/utils/getprocaddr.c
@@ -97,6 +97,7 @@ ctrl_handler (DWORD ctrl_type)
   if (pid == 0)
     {
       printf ("%p\n", (void *)(intptr_t)info->Address);
+      fflush (stdout);
     }
   else
     {
@@ -166,6 +167,7 @@ main (int argc, char **argv)
       if (pid == 0)
         {
           printf ("%p\n", address);
+          fflush (stdout);
           return 0;
         }
       HANDLE main_process = OpenProcess (
```

Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: Ah, nice, this seems to work at least in MSYS2 shell. So, I would apply this patch. But this doesn't seem to work when running with CMD though (I think it's fine to ignore).

Comment (dscho) [reply winsup/utils/getprocaddr.c]: Oh, I _think_ this might be our own fault:

```
  CloseHandle (GetStdHandle (STD_OUTPUT_HANDLE));
```

is called in `ctrl_handler()`, without flushing first.

**Comment by naveen521kk** [comment]
I will rebase this PR based on https://github.com/msys2/msys2-runtime/pull/31#issuecomment-845997395 later today or maybe tomorrow, other than that it is ready.

**Comment by dscho** [comment]
> 
> 
> I will rebase this PR based on [#31 (comment)](https://github.com/msys2/msys2-runtime/pull/31#issuecomment-845997395) later today or maybe tomorrow, other than that it is ready.

Oh, please hold off on that, I am in the middle of editing my version, which I would be happy for you to take once ready.

**Comment by dscho** [comment]
> 
> 
> > I will rebase this PR based on [#31 (comment)](https://github.com/msys2/msys2-runtime/pull/31#issuecomment-845997395) later today or maybe tomorrow, other than that it is ready.
> 
> Oh, please hold off on that, I am in the middle of editing my version, which I would be happy for you to take once ready.

Okay, I managed to run out of time again... But here is something that is relatively polished (except for one fixup on top which still needs testing): https://github.com/dscho/Cygwin-msys2-fork/compare/msys2:msys2-3_1_7-release...ctrl-c-handle-3_1_7

Please do review the differences I introduced and whether you are okay with them.

BTW we could also consider using `CreateProcessW()` to avoid that pop-up console window, but I do not really care as long as calling the helper from the MSYS2 runtime and from `kill.exe` does not have that problem.

**Comment by naveen521kk** [comment]
> Please do review the differences I introduced and whether you are okay with them.

LGTM to me.

> BTW we could also consider using CreateProcessW() to avoid that pop-up console window, but I do not really care as long as calling the helper from the MSYS2 runtime and from kill.exe does not have that problem.

Yeah, me too, I do not care, at least it is internal to msys2-runtime.

I will push that branch here.

**Comment by dscho** [comment]
> I will push that branch here.

Please squash the fixup first (and test, please, pretty please?).

I'm sorry that I haven't been as much help as I originally had planned...!

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (dscho) [reply winsup/utils/getprocaddr.c]: Yep, in my testing, removing this statement fixed the issue!

FWIW this statement was necessary back when we read the output from the spawned process in the MSYS2 runtime _and then_ injected the remote thread _in the runtime_. It was necessary because we needed to flush things and finalize that particular connection so that the spawned process would actually exit.

**Comment by naveen521kk** [comment]
> Please squash the fixup first (and test, please, pretty please?).

Yeah, sure, waiting for the CI, will squash after testing.

> I'm sorry that I haven't been as much help as I originally had planned...!

No problem :).

**Comment by naveen521kk** [comment]
> Yeah, sure, waiting for the CI, will squash after testing.

Ok just tested, things are looking good.

```sh
$ /c/msys64/mingw64/bin/python -c "print('started');import time;time.sleep(3000)"
started
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyboardInterrupt
```

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (naveen521kk) [reply winsup/utils/getprocaddr.c]: > Yep, in my testing, removing this statement fixed the issue!

Hmm, it still doesn't work for me in cmd (got the latest build from CI), but I think that shouldn't be a problem though.

**Comment by dscho** [comment]
> 
> 
> > Yeah, sure, waiting for the CI, will squash after testing.
> 
> Ok just tested, things are looking good.
> 
> ```shell
> $ /c/msys64/mingw64/bin/python -c "print('started');import time;time.sleep(3000)"
> started
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> KeyboardInterrupt
> ```

Yeah!

I guess all that is left to do is to rebase this onto `msys2-3_2_0-release`, right?

**Comment by dscho** [comment]
> I guess all that is left to do is to rebase this onto `msys2-3_2_0-release`, right?

That was a bit trickier than I thought because `winsup/utils/configure.ac` went away between v3.1.7 and v3.2.0. But here it is, the rebased version, in all its very, very, _very_ lightly-tested glory: https://github.com/msys2/msys2-runtime/compare/msys2-3_2_0-release...dscho:ctrl-c-handle-3_2_0

@naveen521kk would you mind testing this? https://github.com/dscho/Cygwin-msys2-fork/actions/runs/900803132 should have a fully-built version soon. I am particularly anxious to know whether it causes a flicker (due to a console window popping up) and whether it works reliably, even with processes that are notorious for not being interruptible (see e.g. https://github.com/git-for-windows/git/issues/2603 and https://github.com/git-for-windows/git/issues/2592 for reports about such processes).

If everything works out all right, I would like to suggest to force-push and to change the target branch by clicking the <kbd>Edit</kbd> button next to the PR title (which does let you edit the title, but also select a different branch).

**Comment by naveen521kk** [comment]
> would you mind testing this? https://github.com/dscho/Cygwin-msys2-fork/actions/runs/900803132 should have a fully-built version soon. 

This works for the python example (`/c/msys64/mingw64/bin/python -c "print('started');import time;time.sleep(3000)"`) but fails with `pip`, ie a wrapped executable which calls python again.
```sh
$ /c/msys64/mingw64/bin/pip.exe check


Naveen@MY-PC MINGW64 ~
$ jinja2-time 0.2.0 requires arrow, which is not installed.
furo 2020.12.30b24 has requirement sphinx~=3.0, but you have sphinx 4.0.2.
astroid 2.4.2 has requirement lazy_object_proxy==1.4.*, but you have lazy-object-proxy 1.6.0.
```
(see it's outputting stuff after being pressing Ctrl+C). From the task manager, I could see `python.exe` wasn't killed when `pip.exe` was killed.

But calling `$ /c/msys64/mingw64/bin/python -m pip check` seems to work, and exists with a traceback.

I will see if this happens in previous versions also.

**Comment by dscho** [comment]
Hrm. We may have to reinstate the strategy to exit entire process trees :-(

**Comment by naveen521kk** [comment]
I think there is something wrong with the stub exe file for pip, I will have a look at them and I also think it would great to exit the entire process tree (I think cmd does that).

**Comment by naveen521kk** [comment]
> Hrm. We may have to reinstate the strategy to exit entire process trees :-(

Ok, there is a bug in those launchers. They try killing python but it simply fails and they don't catch the error. 
Edit: Found the issue https://github.com/pypa/setuptools/issues/337

https://github.com/pypa/setuptools/blob/2234e88b7b820c40f29d7ddadc182b0f130eaa1d/launcher.c#L171-L193

(Btw, `GenerateConsoleCtrlEvent` was having wrong parameter type :facepalm: )

So, that means we got another idea that cmd kills the entire process tree not just the single process, let me try implementing that maybe.

**Comment by dscho** [comment]
> let me try implementing that

Heh, it is my fault: I asked you to switch the order of things by calling `exit_process_tree()` only as a fall-back in `exit_process()`, as opposed to calling `exit_process_tree()` as the top-level entry function.

So this is what we may have to do, I think:

- in `exit_process()`, replace [the call to `exit_process_tree()`](https://github.com/msys2/msys2-runtime/pull/31/commits/922d17b6ca7c898aab632f32ad4e8c83929c35f0#diff-083ad673bed6c3e0d175243e2aa51f3c5ea6576894e2cd06b8c78f654f5da4a1R179) by a call to `TerminateProcess()`.
- in `exit_process_tree()`, replace [the call to `TerminateProcess()`](https://github.com/msys2/msys2-runtime/pull/31/commits/922d17b6ca7c898aab632f32ad4e8c83929c35f0#diff-083ad673bed6c3e0d175243e2aa51f3c5ea6576894e2cd06b8c78f654f5da4a1R272) by a call to `exit_process()`.
- change all outside callers calling `exit_process()` to call `exit_process_tree()` again
- _document very, very well_ why we are not trusting processes to end their child processes upon receiving <kbd>Ctrl</kbd>+<kbd>C</kbd> (looking at you, `pip.exe`) in the commit message of the middle commit.

I am so sorry that I asked you to do work that turned out to be the opposite of what we _actually_ need. My apologies!

File: winsup/utils/getprocaddr.c (hunk 15 above)
Comment (dscho) [reply winsup/utils/getprocaddr.c]: Hrm. I guess we still have to call `fflush(stdout);` manually?

**Comment by naveen521kk** [comment]
I will try getting to this by today.

**Comment by naveen521kk** [comment]
Will squash https://github.com/msys2/msys2-runtime/pull/31/commits/df9881cb3004c38557702d6090149c3353ff8255 into https://github.com/msys2/msys2-runtime/pull/31/commits/922d17b6ca7c898aab632f32ad4e8c83929c35f0 after testing.

**Comment by naveen521kk** [comment]
Ok tested and seems to work
```sh
$ /c/msys64/mingw64/bin/pip.exe check
Traceback (most recent call last):
  File "C:\msys64\mingw64\bin\pip-script.py", line 33, in <module>
    sys.exit(load_entry_point('pip==21.1.2', 'console_scripts', 'pip')())
  File "C:\msys64\mingw64\bin\pip-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:/msys64/mingw64/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:/msys64/mingw64/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
```
so this is ready (only squashing it remaining).

Also, I think it should also fix https://github.com/git-for-windows/git/issues/2603 and https://github.com/git-for-windows/git/issues/2592, possibly it would be great to ask people who opened the issue to test.

**Comment by naveen521kk** [comment]
Hmm, changing the branch simply messed up.

**Comment by jeremyd2019** [comment]
I'm guessing you need to rebase against `msys2-3_2_0-release` and force-push your branch again.

**Comment by naveen521kk** [comment]
> I'm guessing you need to rebase against msys2-3_2_0-release and force-push your branch again.

Yeah, irrc @dscho already did it for me, so it's gonna be simple enough.

**Comment by naveen521kk** [comment]
Done :)

**Comment by naveen521kk** [comment]
@dscho does this look good to you?

**Comment by dscho** [comment]
> 
> 
> @dscho does this look good to you?

Yes!!!

@lazka do you want to give this a final look-over? Otherwise I will merge, and open the corresponding PR at msys2/MSYS2-packages.

**Comment by lazka** [comment]
This is all way over my head, please go ahead.

**Comment by dscho** [comment]
@naveen521kk congratulations, and let me say this: I am very impressed how you kept working on this for three months, with a really nice end result. Thank you!

**Comment by naveen521kk** [comment]
Thank you for reviewing. This helped me to learn C and about Win32 APIs; without you, this will not be possible :).

**Comment by jeremyd2019** [comment]
on arm, running mintty, running clangarm64 python, hitting ctrl-c kills python (after a significant delay).  from windows terminal ctrl-c shows KeyboardInterrupt as expected.  this seems to be expected behavior for lack of arm binaries for the libexec binaries

**Comment by jeremyd2019** [comment]
question: doesn't cygwin provide [`kill(2)`](https://man7.org/linux/man-pages/man2/kill.2.html)?  Why does `kill` util need patching rather than just the `kill` syscall within cygwin?

**Comment by jeremyd2019** [comment]
Does this work on win7?  I could only get python to get a keyboard interrupt if run through winpty.  Otherwise, sometimes python would die, but leave things in a very broken state that never got back to bash.  It appears getprocaddress32 (or 64) hangs around in taskmgr for many seconds, and then both it and python die.

The only reason I tried win7 was to make sure my proposed change to detect arm processes wouldn't blow up there, but I'm seeing the same behavior with that as with the version currently in staging

On Windows 10 I get keyboard interrupt AND python exits when attempting to interrupt `time.sleep` from interactive python

EDIT: I'm sometimes seeing the 'broken' behavior on Win10 too... It appears the 'forked' bash process that supposedly 'execed' python is hanging around.  Killing it returns to the shell.

**Comment by naveen521kk** [comment]
Hmm, I tried to install this version from Pacman(staging repo) today, and I found it wasn't working, there was a long hang and nothing worked, I had to close the Window. I tried the same `pip.exe` I created previously.
[pip.zip](https://github.com/msys2/msys2-runtime/files/6686321/pip.zip)

It was working previously and also works on a fresh installation but not on my old one, and that looked weird.

So, to debug I downloaded [Process Monitor](https://download.sysinternals.com/files/ProcessMonitor.zip) and started to check whether `getprocaddr64.exe` was called. Everything looked normal, except the below one
```
Parent PID: 8528, Command line: C:\msys64\usr\libexec\getprocaddr64.exe CtrlRoutine 0 13267416829, Current directory: H:\mingw\test_programs\likefinal\, Environment: 
	MSYSTEM=MINGW64
	PATH=...
	SYSTEMDRIVE=C:
	SYSTEMROOT=C:\Windows
	WINDIR=C:\Windows
```
When starting `getprocaddr64.exe` runtime is calling/passing a significantly large PID `13267416829`, will this even happen? 
In procmon the PID for `pip.exe` was `7344` and `python.exe` was `2228`.

Next up, this one
```
PID: 7720, Command line: C:\msys64\usr\libexec\getprocaddr64.exe ExitProcess 130 132674168
```
Again, a large PID but different from the previous one. As expected `getprocaddr64.exe` exited with status 1.
This happened twice and then finally, `pip.exe` was killed using `TerminateProcess` still `python.exe` is alive though and terminal was hanged(maybe the forked process executing python was hanging around ).

I wondering why this happens that too only in the main installation.

**Comment by naveen521kk** [comment]
Hmm, the same number comes up  
```
PID: 2720, Command line: C:\msys64\usr\libexec\getprocaddr64.exe CtrlRoutine 0 13267416829
```
`pip.exe` pid -> `8332`

Next, I tried placing the build from this PR on the tree and now it still hangs but the numbers changed and I think something is going wrong
```
PID: 8092, Command line: C:\msys64\usr\libexec\getprocaddr64.exe CtrlRoutine 0 13268512904
```
Even on second time it was same number.

**Comment by dscho** [comment]
That is really strange. I thought maybe the `pid` was formatted using the wrong `printf()` format, but no, it is a `DWORD` and it is rendered using `%ld`... Puzzled.

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 41]
```diff
@@ -0,0 +1,282 @@
...
+      if (!i)
+        process = main_process;
+      else
+        {
+          process = OpenProcess (
+              PROCESS_CREATE_THREAD | PROCESS_QUERY_INFORMATION
+                  | PROCESS_VM_OPERATION | PROCESS_VM_WRITE | PROCESS_VM_READ,
+              FALSE, pids[i]);
+          if (!process)
+            process = OpenProcess (PROCESS_TERMINATE, FALSE, pids[i]);
```
Comment (jeremyd2019) [inline winsup/cygwin/include/cygwin/exit_process.h:265]: Should probably have `PROCESS_QUERY_LIMITED_INFORMATION` here too, to be able to query PID and exit code.  Assuming nobody here cares about anything older than Vista, on XP you need `PROCESS_QUERY_INFORMATION`.

**Comment by naveen521kk** [comment]
> Does this work on win7? I could only get python to get a keyboard interrupt if run through winpty. Otherwise, sometimes python would die, but leave things in a very broken state that never got back to bash. It appears getprocaddress32 (or 64) hangs around in taskmgr for many seconds, and then both it and python die.

Seems related, I was also testing on win7. Though in my case `getprocaddr*.exe` didn't hang instead it got a wrong argument.

**Comment by naveen521kk** [comment]
Hmm, I just downloaded https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.tar.xz extracted it added the Pacman staging repo and updated runtime. There it is worked perfectly
```py
$ /h/mingw/test_programs/likefinal/pip.exe
start
Traceback (most recent call last):
  File "H:\mingw\test_programs\likefinal\pip-script.py", line 34, in <module>
    time.sleep(4000)
KeyboardInterrupt
```
So, I think it isn't a problem with code here.
Maybe something messed up with the original installation?

**Comment by jeremyd2019** [comment]
That doesn't make any sense, msys2-runtime is/should be self-contained

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 42]
```diff
@@ -0,0 +1,282 @@
...
+  wchar_t wbuf[PATH_MAX];
+
+  if (cygwin_conv_path (CCP_POSIX_TO_WIN_W, name, wbuf, PATH_MAX)
+      || GetFileAttributesW (wbuf) == INVALID_FILE_ATTRIBUTES)
+    return NULL;
+
+  STARTUPINFOW si = {};
+  PROCESS_INFORMATION pi;
+  size_t len = wcslen (wbuf) + wcslen (function_name) + 3 /* exit code */
+               + 1 /* space */ + 10 /* process ID, i.e. DWORD */ + 1 /* NUL */;
```
Comment (jeremyd2019) [inline winsup/cygwin/include/cygwin/exit_process.h:79]: I think this is missing 2 spaces (space between `wbuf` and `function_name`, and space between `function_name` and `exit_code`.  Also, is it safe to assume `exit_code` will always only be 3 digits?  It seems so because the callers use `exit_code & 0x7f`, or else `CTRL_C_EVENT`/`CTRL_BREAK_EVENT` which are 0 or 1 resp.

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 43]
```diff
@@ -0,0 +1,282 @@
...
+ * TerminateProcess() function.
+ */
+static int
+exit_process_tree (HANDLE main_process, int exit_code)
+{
+  HANDLE snapshot = CreateToolhelp32Snapshot (TH32CS_SNAPPROCESS, 0);
+  PROCESSENTRY32 entry;
+  DWORD pids[16384];
+  int max_len = sizeof (pids) / sizeof (*pids), i, len, ret = 0;
+  pid_t pid = GetProcessId (main_process);
```
Comment (jeremyd2019) [inline winsup/cygwin/include/cygwin/exit_process.h:197]: Why is this `pid_t` and not `DWORD`?  This is a Windows PID, not a cygwin PID.

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 44]
```diff
@@ -0,0 +1,282 @@
...
+  int signo = exit_code & 0x7f;
+
+  pids[0] = (DWORD)pid;
```
Comment (jeremyd2019) [inline winsup/cygwin/include/cygwin/exit_process.h:200]: Then this cast would be unnecessary

File: winsup/cygwin/include/cygwin/exit_process.h [hunk 45]
```diff
@@ -0,0 +1,282 @@
...
+              pids[len++] = entry.th32ProcessID;
+              break;
+            }
+        }
+      while (len < max_len && Process32Next (snapshot, &entry));
+
+      if (orig_len == len || len >= max_len)
+        break;
+    }
+
```
Comment (jeremyd2019) [inline winsup/cygwin/include/cygwin/exit_process.h:251]: `CloseHandle(snapshot);` ?

**Review by jeremyd2019 — COMMENTED** [review]
Going through this code looking for *something* that could be causing issues...

**Comment by jeremyd2019** [comment]
I guess now that this is merged I should make my own pull request instead of review comments suggesting code :grin:
